secret_prometheus_remote_write:
    username: ENC[AES256_GCM,data:t2Bztgi43oD4WMFhmY3FpRdlDyA=,iv:LIa8K9abTtZRp7H+/hegVjZ7UEjZBfOJrifFjUNyI+w=,tag:os9IHIQmq/AGOZ5/4lktSg==,type:str]
    password: ENC[AES256_GCM,data:hp8AYCpRfWjy9vmN9azJWGWoaWAoGR7cLANdNOq33bySXJ31,iv:JHN/FpLTd7wtIJxnhZlMfDwzcWDcodANwA2WE84s/S0=,tag:fOD7O+0UCSN4p6IWNmZG2g==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:dgcAuyRcID1/Ou2vRCe6kO5aBSX+YOBIJVHz5WYSxDw29V/g+IjNZaf94auX/Dg9OQ0C1jw9+Ro=,iv:skLk09esJqAP2Y9O3XOnPTiniWp/DSzghb6ILp/MU7g=,tag:78yI0sGaXLYOneFJTKgYzQ==,type:str]
    username: ENC[AES256_GCM,data:Vjy0S0KnGa0MRakF0V2rRr1kKZw=,iv:0ZvfuTSBAsbTzdTXbdbczwg4WsZXw/o2H/mLhVXyg+E=,tag:odpvM2SZAydSRfe2l5bNcw==,type:str]
    password: ENC[AES256_GCM,data:PwAonLXL5a5UFGH4RkGpJwWW0VukO5b+ZS6xOh6G6jYkp0wW,iv:gTvdMtsEDzSxH0OQRYYzXXTaG26W8HC13aTXz9waJrA=,tag:l0dLTLFObaHmOtwev9J87g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzmeqmpu70anvkt78pl5y0w67r6jpdkamr4cr95mts9vthjly58qfctt55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNkFYUVJaaDkwUzRENHRJ
            aXR0dkFiNkxZVEhRUnpwc1NFWnROamtZMlZFCkdoOGMxMUp4NlN5elM0RzcvaXhs
            WkZzcDE2TVNmbzRyQVpxeXRMdm10Z1UKLS0tIGZDZVp3U2ZDS2prcEZPeGl4VGN1
            QVFIS3pXNXhFQUtHU01sMDNpL1V3ZTgK2Thj7i4RSVt8Eg8Dxv93uy3u+kdasvoG
            vbfqryrgpcqL6pHXgbGtU3gyCBOAkMWiX0lXua6lmeV8bWaqhrrllg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T05:13:47Z"
    mac: ENC[AES256_GCM,data:iXjQqgMLVHQp7mUfBVcCQubIiYqrZuumqKLV2gK7XZHjBtHkx3VlcEQk+b5QBao/OLi2sjB+dEw//pmPdedmbcqyaAJ2zuYr0aNftGZJIhVTgqzX454NJfvquX3QemeLybcugWv0IX6wVBtTy1LXZ0SFMStIr4I4DfISR8ZFyBY=,iv:IoYHDzADLBqgmmkBVMtfJ55ZUVcRlg+FLQ5oMbiFAU8=,tag:mMxJURYCrMV+0EL5kXpsQw==,type:str]
    pgp:
        - created_at: "2026-10-08T05:13:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA+2+1l9DpxI8AQ//ap2COrYSIyXtS6jelwS40KdNW7PFskS45eIi2JdT0N2N
            9cupwrnGsm1fKBIQUGq4G32TlkjTlJBkMvuiC/duosO5TH1EcAr/UG7Flq3/X2qv
            VuYG4AFG6G8BlYN/cZ5NQkoWDb4Ad76aS4ywzq7yxJBfqbXOVigKk2iiknbed9W1
            d/2+fOiOT5zYvnY/p/s4Z+5rtQbll7QshB6Xh8QCJAKS8mxuzgitRz3L/eIxbwev
            TI5NMrUs+2kiWUPulEiCo+sXXcHsAIYkNExdywewlYzoKunOLtp3e4MroGXMFOgg
            vt0TLc9Uq7nSCzgv5y2O/DwZOFV021BWnQGeeTMhKXl7pA4F3uB2JWODAGExLyC4
            6SJUH+xfoFK+PQRhAmNtCrp5m/omwKURQPGqmx/wI5EelSL2REA+6rjiJP5rK9Cm
            +CkZqQoyC1mQsz6QvdEHZOf4v8galz0AeLD5hq+gvKbNmd145JkT1ipTlPfiecNA
            IiSYGsYjIil8D1QWBR1ZHG7McRpMtl4i5cwrbmP2NdCwfkp4LLxknvLaYLEFocoK
            1+ull9gj+4UJJkDG2PJA4LcTE67TwlJBN/Yfp1/BxOUiM4YSk1ShOAF1t3AnOMFc
            7zmOig9xGRWFgWuOOklABdnDibpPK0sbq570+FUTO4xLvh+En7ogn1zUIS2UAL7S
            UQENYmTSELw/OawC3iGWzuoDbrVmBUuJLl+YP+JHIi4ve5GtZ5nEWyE2UES2Mqom
            E3amteqj4yrmbqUgcJlGvqs41CiNQP5+2piz9wEQaoANRg==
            =XRNc
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-10-08T05:13:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA87Wber4r4dGARAAzIxnN9awSW0M+Wcg3idOxY5XKPHY79mre/NGcXj/G5Zb
            1Hwv5l/YD4y4mtuklL14b3OJJNi1+w7+ctw9Dxsv6Xrla9JcI4s61d5WDrCL6Jvb
            rWhSQeFyHpu7sMddPbft1QeyGmT6PMADFvN964s+DV7jfuxeqKtgxUxMC3qqIQkd
            xTH2iNlYB57kYqJJZ4ETmyNcci46vzcVY8c9r1eKtESlvvls2TnvrTIwiSnHbbkF
            Z5vRhUqTB0LAhT22Jqk+UsnLz03z4ZDN082HJDE9E4AtFB3ZM9IJRqX3/ZTyfvfT
            0XsF4vwqJrV250aTxOjTNu4SUZTTnUFtC01C4DxO5QcVoIib4e63xR3SW9JmNvo4
            hBKoo82oNYdqbQ7owimP1xSana6jdt7IiGfpsUi3q4V3iCWu0Mfxr1EZf5LAe4r9
            9POLa+ug9Jq5j20MiDB8Yx3+kVc+dnqB9FQCZzfhw3nq7090/YUePTzaa9PQRkZH
            HOEiliOM/JH3e9AaspQx/XoD20E/9/OOXRDZ/OST4ZSl2WflR9lFqV3dv5TVQxIA
            kIYxWplvfiQSbZgJwQvSvjXCBebBbzEnL/cr7aXJUcUd8Rc86Yqadb6sSSpZI/RO
            nzAEkwspRIbax0MrFzA9qCbvwoLrQ9KSP87PFxKWAPeJIcd2/9N90L0pVvCQEtXS
            UQHLfsS6WkYbPJ2z8NVU4wmiaJDvOvFjSc6WSvJCzG8ynCM8yzPtzk0ZhbIrDHGj
            HdqsfHyzTJZcy71xRFzonpilNNlxoatadBSnTjWPpKRpdA==
            =Z3uA
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-10-08T05:13:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAqn9ZtCMtgdytHoxnXaK5ChaW1oVCFyY8KbQhlrVWuxkQ
            BcMABVK/IO55+KEiYCJBwZjgn3CfkH5gATjMBG/4cPTlrE42kVyRkZLUnnMFCuhj
            q/rChe94skcpaNeTjya6clhDmTCjBOJIwSjy7cYRwqoeaGc9uIMqpCTdLahkyTQx
            6g7ToXQ/KAOEeeVOMGm+ElA+rxcT7gpdGZSBPbFqFHm70Kyc3lDcHTHUk8tVer+n
            Ky3zwnqhc/pKsgicCvBoxUtD4lYDdoCuYoQ3TlTYB6Be+0ClvBFLfuJIVoMMyqOq
            M8vLjk7UmW3PH4ThNYyVKQcLW/NyOgPLPRoW1ANxRGoBig69HOKOOAeL2oqKjjsW
            iacwkLkLUa+7WEqNduu4X0TkHpZ+UzyJv9bxkkE50vbZgjGkorPvIs8jjFaJD/bG
            RE2Frz5TqAl68T+MGwE5FmKCALk+/VYzcoED1zPIYLQbb4MK2CeUup/zwLV6XlVT
            4ECEAk/bgqgx+jqwlxfSVBxXrsdtD4/+AtKm0s2F2CSv2BMr1938wjBhEu+xNBwx
            vgBYPNChpVXVo0oPJ6ITFTE7x/fWTW/pZPL6muO/fPHjQpyDG8B9rrAF4CFgug/V
            u3yzDtym6BkApkx/Defn7qDUKwF3fBcUBShxvrRBZoHWUiY55oRONeLl6jHn437S
            UQFC4qu0sJOs8NIkhh/EjU0zfh+GkRDZ1OfWgUG8ZDweh6Sx/qTAWR5WQx2Q9OiE
            ZwwbsxU09Yc1ugQ8IA96FaX4CQ5iiQ1ZnubS6hWzjlY/Yw==
            =WvMG
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-10-08T05:13:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAw01qfIBwY0JAQ//cemgJ7beooWUjCQ6KRl8D0WFNqraibVBC6jDnnfxRMVu
            WvFfeWtOFl83Yw5gICnsI/Qzbyt1VGv1qWDKw+inHW7RodMLtpTKP2wS25m7/F0P
            z47DCLPvb0nCmKZNvq8p/lSPMKk7RhEyJDe1JE6V38nqF8H2OQd+L+MlW5nNF+P8
            GlGdZUGWc4lmZ+kVrAtQqnT3Ng+5rETInCK75ustRuaZWWxPDcLSZx+FTaB653p5
            AkO8voZB1FG5dfZt6RpIxB5aGy0HlPuIUZTVh1kncNv/j2JIvWjErTHkKozYWbb1
            3XgFaEi8Q0AahQ9A00xZPNwEt3E1qMA2oO7AiUKIhsl4stnaW5MFrH2ApYMgNLhi
            XN0QsFQQ98jNEsmoX7rUA1UefOPBqm/BzzQ/tBcPkY5ZXk1Db5HAP5yLW1JpAsuA
            PbFeHtJraAmXNqkQ8yMrMlwMDrSN1poJOtRABYme32fY11PtWFnpiku/WwVDxyi9
            cKiWAzBu2f5TP0xSdWIUEsvq6PtauAT8q7pACVu9haBx/n4wu8lztlf2Gg8EB2NU
            gt4OkN1shc6I/p2NYNOAPOD7pTQmmaT+Blf9gFByf1HB0io1Lhhn4Ab15ojXsAtE
            O+0F+mO6ZVrHxIOrBSZC9CUx0vZtpXmYHuTk5O0GltVDfwOhna0rDpfonayqYkHS
            UQGEItsG4DyQdFt0gZF1X5/kQzCXrdz7ZElXvuH2oweKt4wjKI6RIFwbUj5rHcMi
            F5o4X+AJ43yiI63bYCLrq3coYg9B4R4zBPHFvwaHApqopw==
            =0hw7
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-10-08T05:13:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAwDFOgk9tOQ+AQgAkqSZuYs7/qsYdUBh/S0brj5AnnSNOndcOR06wo2CR6o3
            BHhOa5PfcABF4s1iaJiQtTssZynIrClW1LEguCrkzxc9eDCkeO8+cpG7vyRE8+G2
            mL/w7MR2GRqEvMZ4wfkJSjD/GWC/bv7pjpXi5Jd+lOo4wKOujOSolsI4QkbiauC0
            ZqnUhuVQ/9EdnMHKrt5SG9syk70W2IO6Uj6IXFUdTShocO1byqqt0FRlbdiXGJl9
            Bf7+7eu2hfd0ms5MOzBUG/cWuzEdplYbYxmV556v4xcd01GpgRaNg/2CBq/RNUkf
            mdhq8JEecEe4WizhQYTI0kt+v72DWP9FMiz+25jt39JRAVKhw749s5wyRX7r2D8T
            Vatr3pKmk3AMUT74qr22kviAYupZZUNvbmzWGp4W7EX3WxTc/eL0G7Z6M8Z0lUfc
            CCZvx5YJaxkxPuSUarUtzZt6
            =vDxI
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-10-08T05:13:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAz4a8AV36xppAQ/+K+fOAyQ3/wSUoR59Oj29Cq620IJL/kHvecpZvA9ClxyD
            d0aENiU1bSRM051L/XRfuEbYza5MKk4eAZmdDNi0IGrXc/C6Cb5+9HcBjxrehs4m
            WfXLgjuFP0Mlv/FRyDM6zqkttrWF90PTIKxmQUIbu89Zi1bkW8Y7GR4KEvRZs86X
            YPUw7BYx4UfdqAetM9YxKlTGXpHWiCWs2ucLvHwq93Z1oJu3UF9HRDhAiAWFLhJc
            tbvGBLEufZ52o4e20+FIwkvOEXd01tsWYCfbNuh6i1T9kZ/+uj9N9zIrRutfTghH
            VrgVAPHOHNJLcUUJq9DBsnwfUPs7EmxyhBeRFin2vvTCumndp2n9xwJqZsn/MX7l
            Dv3bkeRwrQbkedW3Br1flKT5IX8ywKCbfFGdg6H0GT8KjGurAvB+wmfB/kdFNQb6
            ZmaLkld2oPJr17bFWX+kiCK0b6KMsANswWd96gY+cVQEKgke8fS+s8cOMz8VsKOP
            eaIpKw3UPbIP09Sk4w3kH15Yew7ABzZ3jgu1uK62JZOrbyqAglQxQadu/r9IvZ57
            qU8f7DqM/xKSE1qyF7WAdYcjFBBVXrsDZiP4Nyow+5/zL/SjmFqMzCSJHD2nV3fv
            Sgjh5/TMtcu7pGCkJyNwRnXbNMj5hH4sxxYZrjPObmY8Wy0M3FHpI4risSr8CCnS
            UQGiBwzcr+3mPFJOaYijDXJb6AprV524j+a6rEwWEjBBH8C0ewFurZQOoEey6kh8
            DODSJhgW/CsOAHx+1n817VJ3I4WgCQfj4N7zqC8FCRl5dg==
            =OjKi
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-10-08T05:13:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/+NqDxNrUGh+zyXOfMM76atWuX+BDrpv5Nil7qBilgUVNr
            n7088k9jxk+Iq5aRJEDZ2v6dEzRN9qP8KKehwBudlwyoF0Xt1ghZWICLju7+biXn
            wYm7Gl+OPQprgim6evIpR9r6yOZvpbn5vdKUA0fC4QP157kItplpXvEu3upzama9
            qjjvZ1wgxqlT8S1b3dNw1WxfXtHoyS3eG3aEEpZRtEZilsfkL16lqiCkHjiXmuN7
            NVrZCdTr4jNW+CWxszC9RT9fgYmiLIprRVfAZuppVyUlqPIHTz9JOHrJ5YbqmQaE
            CdZGDlBKFtBeWm4Kd8O73BxQGYHTmI5MBhOtg8FKCDN0IxbezGCWOqNy8wyHmZl2
            c0fbzgA9x6y8BpBkiwmSxfzD3ZQT4k6XziwAsZBDIXlWCJx8+WbDIJE3GSzrj6Qz
            sPX5FADDDjboLzl3FKm8a+qQChPHZSj2KcxBD5TnjCRurMP9EUZEQxt8Q9pJoQZm
            sTePNpOCnXuL34tjW8MrE3Ghd/1/N61lIOT039c3Io18QG0tJiQTClLzhWEP1frq
            AYWXPTXPtCDClFYoGbFQhBYp/U7hEtdWz+tWcT+YyWPbJiIqL59/7rZVUezBeHrv
            spnVwORDq8beseh4QFJsMTdlJdu+UAJ96WzFZ5d04VxSVq851qYucAB3yhiwi5vS
            XgGAr3FnF2F8xP+v+fo/gjOHve6jIIwxNv1hQ9s2WR6QscGNE8CQQhBl7YitgBak
            Buf89wSXohZb8slco05x13cvmF8AWMcnoxRRj53Apog/VKV/VbYsk+0EwdPcVrI=
            =L96m
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-10-08T05:13:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdA0z+QLSZXYsgNqzv0aWfkkswSXH21xADc0WSCV4lO/1Yw
            uNI6OE4DRyPhrgACI5ybO1b+SBgZqVBF8BPfvZMzyCg1aE0WwZSryoyszj5lLWQr
            1GgBCQIQVLVXb4z0F1Lo9PYUC2xG2s7K+hVfv7l5EZI93+siMPJ/NVOrHtfDkCli
            NdnG6YvnOBLLVAkoiL24mGB9jolgnWIMdk7/HfSj5mr3auRiLvCXs1HLDfRDgox0
            wXYLE1Of07Sg0g==
            =zyZs
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
