localhost

[all:vars]
ethereum_network_name=glamsterdam-devnet-1

[bootnode]
bootnode-1 ansible_host=138.201.190.180 ipv6=2a01:4f8:c014:8d6::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True 

[buildoor_prysm_geth]
buildoor-prysm-geth-1 ansible_host=178.105.71.120 ipv6=2a01:4f8:c014:ad09::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=False 

[lighthouse_ethrex]
lighthouse-ethrex-1 ansible_host=46.225.148.18 ipv6=2a01:4f8:c014:3bcd::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=2500

[lighthouse_geth]
lighthouse-geth-1 ansible_host=178.105.30.138 ipv6=2a01:4f8:c014:73f4::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=500

[lodestar_ethrex]
lodestar-ethrex-1 ansible_host=178.104.215.215 ipv6=2a01:4f8:c014:691f::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=3500 validator_end=4000

[lodestar_geth]
lodestar-geth-1 ansible_host=162.55.41.177 ipv6=2a01:4f8:c17:a63b::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=1500 validator_end=2000

[prysm_ethrex]
prysm-ethrex-1 ansible_host=178.105.68.98 ipv6=2a01:4f8:c014:a09d::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=2500 validator_end=3000

[prysm_geth]
prysm-geth-1 ansible_host=178.105.71.84 ipv6=2a01:4f8:c014:a5c9::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=500 validator_end=1000

[teku_ethrex]
teku-ethrex-1 ansible_host=178.105.66.240 ipv6=2a01:4f8:c014:8c43::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=3000 validator_end=3500

[teku_geth]
teku-geth-1 ansible_host=178.105.26.245 ipv6=2a01:4f8:c014:7cfc::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1500


[lighthouse_reth]

# Consensus client groups

[lighthouse:children]
lighthouse_ethrex
lighthouse_geth
[lodestar:children]
lodestar_ethrex
lodestar_geth
[nimbus:children]
[teku:children]
teku_ethrex
teku_geth
[prysm:children]
buildoor_prysm_geth
prysm_ethrex
prysm_geth
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
buildoor_prysm_geth
lighthouse_geth
lodestar_geth
prysm_geth
teku_geth
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]
[ethrex:children]
lighthouse_ethrex
lodestar_ethrex
prysm_ethrex
teku_ethrex

# Buildoor host aggregator

[buildoor:children]
buildoor_prysm_geth

# Global groups

[consensus_node:children]
lighthouse
lodestar
prysm
teku
buildoor

[execution_node:children]
ethrex
geth
buildoor

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
