localhost

[all:vars]
ethereum_network_name=glamsterdam-devnet-2

[bootnode]
bootnode-1 ansible_host=159.223.181.57 ipv6=2604:a880:400:d1:0:4:5963:6001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True 

[buildoor_prysm_geth]
buildoor-prysm-geth-1 ansible_host=198.211.107.240 ipv6=2604:a880:400:d1:0:4:5963:9001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False 

[grandine_besu]
grandine-besu-1 ansible_host=159.223.170.9 ipv6=2604:a880:400:d1:0:4:5961:2001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6500 validator_end=6600

[grandine_ethrex]
grandine-ethrex-1 ansible_host=165.227.80.203 ipv6=2604:a880:400:d1:0:4:596f:c001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=7000 validator_end=7100

[grandine_geth]
grandine-geth-1 ansible_host=143.198.124.105 ipv6=2604:a880:400:d1:0:4:5961:3001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6300 validator_end=6400

[grandine_nethermind]
grandine-nethermind-1 ansible_host=104.248.239.38 ipv6=2604:a880:400:d1:0:4:5963:a001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6400 validator_end=6500

[lighthouse_besu]
lighthouse-besu-1 ansible_host=67.205.181.133 ipv6=2604:a880:400:d1:0:4:5961:9001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=4000 validator_end=4250
lighthouse-besu-2 ansible_host=146.190.82.185 ipv6=2400:6180:0:d2:0:2:d822:c000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=4250 validator_end=4500

[lighthouse_ethrex]
lighthouse-ethrex-1 ansible_host=159.89.233.230 ipv6=2604:a880:400:d1:0:4:596f:b001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6600 validator_end=6700

[lighthouse_geth]
lighthouse-geth-1 ansible_host=162.243.166.74 ipv6=2604:a880:400:d1:0:4:5961:6001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=250
lighthouse-geth-2 ansible_host=139.59.255.2 ipv6=2400:6180:0:d2:0:2:d822:1000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=250 validator_end=500

[lighthouse_nethermind]
lighthouse-nethermind-1 ansible_host=208.68.39.71 ipv6=2604:a880:400:d1:0:4:5961:7001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=2250
lighthouse-nethermind-2 ansible_host=206.189.85.47 ipv6=2400:6180:0:d2:0:2:d822:4000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2250 validator_end=2500

[lodestar_besu]
lodestar-besu-1 ansible_host=137.184.199.142 ipv6=2604:a880:400:d1:0:4:5961:4001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=5500 validator_end=5750
lodestar-besu-2 ansible_host=174.138.28.114 ipv6=2400:6180:0:d2:0:2:d821:e000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=5750 validator_end=6000

[lodestar_ethrex]
lodestar-ethrex-1 ansible_host=206.189.177.40 ipv6=2604:a880:400:d1:0:4:596f:f001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6900 validator_end=7000

[lodestar_geth]
lodestar-geth-1 ansible_host=104.248.113.203 ipv6=2604:a880:400:d1:0:4:5961:c001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1500 validator_end=1750
lodestar-geth-2 ansible_host=143.198.94.12 ipv6=2400:6180:0:d2:0:2:d822:d000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1750 validator_end=2000

[lodestar_nethermind]
lodestar-nethermind-1 ansible_host=137.184.111.109 ipv6=2604:a880:400:d1:0:4:5961:b001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=3500 validator_end=3750
lodestar-nethermind-2 ansible_host=157.245.198.58 ipv6=2400:6180:0:d2:0:2:d822:6000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=3750 validator_end=4000

[nimbus_besu]
nimbus-besu-1 ansible_host=143.198.123.98 ipv6=2604:a880:400:d1:0:4:5963:8001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6200 validator_end=6300

[nimbus_ethrex]
nimbus-ethrex-1 ansible_host=159.223.139.234 ipv6=2604:a880:400:d1:0:4:596f:e001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=7100 validator_end=7200

[nimbus_geth]
nimbus-geth-1 ansible_host=134.209.69.48 ipv6=2604:a880:400:d1:0:4:5961:d001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6000 validator_end=6100

[nimbus_nethermind]
nimbus-nethermind-1 ansible_host=142.93.117.175 ipv6=2604:a880:400:d1:0:4:5963:5001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6100 validator_end=6200

[prysm_besu]
prysm-besu-1 ansible_host=143.198.168.177 ipv6=2604:a880:400:d1:0:4:5961:e001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=4500 validator_end=4750
prysm-besu-2 ansible_host=68.183.189.54 ipv6=2400:6180:0:d2:0:2:d822:9000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=4750 validator_end=5000

[prysm_ethrex]
prysm-ethrex-1 ansible_host=137.184.193.193 ipv6=2604:a880:400:d1:0:4:596f:d001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6700 validator_end=6800

[prysm_geth]
prysm-geth-1 ansible_host=24.144.109.51 ipv6=2604:a880:400:d1:0:4:5961:f001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=500 validator_end=750
prysm-geth-2 ansible_host=188.166.237.55 ipv6=2400:6180:0:d2:0:2:d822:5000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=750 validator_end=1000

[prysm_nethermind]
prysm-nethermind-1 ansible_host=161.35.112.45 ipv6=2604:a880:400:d1:0:4:5961:8001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2500 validator_end=2750
prysm-nethermind-2 ansible_host=157.245.62.3 ipv6=2400:6180:0:d2:0:2:d822:a000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=2750 validator_end=3000

[teku_besu]
teku-besu-1 ansible_host=161.35.57.135 ipv6=2604:a880:400:d1:0:4:5961:a001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=5000 validator_end=5250
teku-besu-2 ansible_host=206.189.33.56 ipv6=2400:6180:0:d2:0:2:d822:3000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=5250 validator_end=5500

[teku_ethrex]
teku-ethrex-1 ansible_host=165.227.90.118 ipv6=2604:a880:400:d1:0:4:5970:1 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=False validator_start=6800 validator_end=6900

[teku_geth]
teku-geth-1 ansible_host=159.223.136.255 ipv6=2604:a880:400:d1:0:4:5961:1001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1250
teku-geth-2 ansible_host=152.42.251.52 ipv6=2400:6180:0:d2:0:2:d821:f000 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=1250 validator_end=1500

[teku_nethermind]
teku-nethermind-1 ansible_host=162.243.167.76 ipv6=2604:a880:400:d1:0:4:5961:5001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=3000 validator_end=3250
teku-nethermind-2 ansible_host=188.166.232.136 ipv6=2400:6180:0:d2:0:2:d822:0 cloud=digitalocean cloud_region=sgp1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=3250 validator_end=3500


[lighthouse_reth]

# Consensus client groups

[lighthouse:children]
lighthouse_besu
lighthouse_ethrex
lighthouse_geth
lighthouse_nethermind
[lodestar:children]
lodestar_besu
lodestar_ethrex
lodestar_geth
lodestar_nethermind
[nimbus:children]
nimbus_besu
nimbus_ethrex
nimbus_geth
nimbus_nethermind
[teku:children]
teku_besu
teku_ethrex
teku_geth
teku_nethermind
[prysm:children]
buildoor_prysm_geth
prysm_besu
prysm_ethrex
prysm_geth
prysm_nethermind
[grandine:children]
grandine_besu
grandine_ethrex
grandine_geth
grandine_nethermind

# Execution client groups

[besu:children]
grandine_besu
lighthouse_besu
lodestar_besu
nimbus_besu
prysm_besu
teku_besu
[ethereumjs:children]
[geth:children]
buildoor_prysm_geth
grandine_geth
lighthouse_geth
lodestar_geth
nimbus_geth
prysm_geth
teku_geth
[nethermind:children]
grandine_nethermind
lighthouse_nethermind
lodestar_nethermind
nimbus_nethermind
prysm_nethermind
teku_nethermind
[erigon:children]
[reth:children]
[nimbusel:children]
[ethrex:children]
grandine_ethrex
lighthouse_ethrex
lodestar_ethrex
nimbus_ethrex
prysm_ethrex
teku_ethrex

# Buildoor host aggregator

[buildoor:children]
buildoor_prysm_geth

# Global groups

[consensus_node:children]
grandine
lighthouse
lodestar
nimbus
prysm
teku
buildoor

[execution_node:children]
besu
ethrex
geth
nethermind
buildoor

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
