---
default_ethereum_client_images:
  lodestar: ethpandaops/lodestar:deathstar-devnet-6
  ethrex: ethpandaops/ethrex:glamsterdam-devnet-6
lodestar_validator_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --graffiti=deathstar-{{ ansible_hostname }}
  - --defaultGasLimit=190000000