erigon_container_command_extra_args:
  - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
  - --http.vhosts=*
  - --ws
  - --networkid={{ ethereum_network_id }}
  - --db.size.limit=500GB
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --log.console.verbosity=debug
  - --pprof
  - --pprof.addr=0.0.0.0
