# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/forkmon.yaml.j2

forkmon:
  fullnameOverride: forkmon
  image:
    repository: registry-1.docker.io/skylenet/nodemonitor
    tag: darkmode
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.1.js" integrity="sha384-icGX6g6CzB0tqlhDc6Su4c6IPVbcbUvfM3xjbbFYsYBwuZR79WkmOxDhGEPfmyn2" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: forkmon.glamsterdam-devnet-10.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  network: "glamsterdam-devnet-10"
  endpoints:
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.glamsterdam-devnet-10.ethpandaops.io
    name: bootnode-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-bootnode-2.srv.glamsterdam-devnet-10.ethpandaops.io
    name: bootnode-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-bootnode-3.srv.glamsterdam-devnet-10.ethpandaops.io
    name: bootnode-3
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-bootnode-4.srv.glamsterdam-devnet-10.ethpandaops.io
    name: bootnode-4
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-buildoor-prysm-geth-1.srv.glamsterdam-devnet-10.ethpandaops.io
    name: buildoor-prysm-geth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-buildoor-prysm-geth-2.srv.glamsterdam-devnet-10.ethpandaops.io
    name: buildoor-prysm-geth-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-buildoor-prysm-geth-3.srv.glamsterdam-devnet-10.ethpandaops.io
    name: buildoor-prysm-geth-3
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-buildoor-prysm-geth-4.srv.glamsterdam-devnet-10.ethpandaops.io
    name: buildoor-prysm-geth-4
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-1.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-1000.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-1000
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-123.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-123
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-147.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-147
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-172.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-172
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-196.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-196
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-220.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-220
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-245.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-245
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-25.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-25
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-269.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-269
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-293.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-293
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-318.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-318
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-342.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-342
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-366.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-366
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-391.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-391
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-415.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-415
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-440.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-440
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-464.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-464
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-488.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-488
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-50.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-50
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-513.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-513
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-537.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-537
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-561.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-561
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-586.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-586
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-610.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-610
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-635.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-635
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-659.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-659
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-683.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-683
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-708.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-708
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-732.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-732
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-74.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-74
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-756.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-756
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-781.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-781
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-805.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-805
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-829.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-829
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-854.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-854
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-878.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-878
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-903.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-903
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-927.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-927
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-951.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-951
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-976.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-976
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@rpc-prysm-geth-98.srv.glamsterdam-devnet-10.ethpandaops.io
    name: prysm-geth-98

  config: |
    # How often to reload data from the nodes
    reload_interval = "10s"
    # If specified, a http server will serve static content here
    server_address = "0.0.0.0:{{ .Values.httpPort}}"
    # Shown in the document title, if specified
    chain_name="{{ .Values.network }}"
    # Local or non third party connection require rpc kind
    {{- range .Values.endpoints }}
    [[clients]]
      url  = {{ .addr | quote }}
      name = {{ .name | quote }}
      kind = "rpc"
    {{- end }}
