# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: https://rpc-bootnode-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-bootnode-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-buildoor-prysm-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: buildoor-prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-buildoor-prysm-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-grandine-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: grandine-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-grandine-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-lodestar-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: lodestar-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-lodestar-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io
  name: lodestar-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-nimbus-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: nimbus-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-prysm-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-prysm-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io
  name: prysm-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-teku-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io
  name: teku-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-geth-1.srv.glamsterdam-devnet-3.ethpandaops.io:8961
- url: https://rpc-teku-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io
  name: teku-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-geth-2.srv.glamsterdam-devnet-3.ethpandaops.io:8961
