# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/checkpointz.yaml.j2

checkpointz:
  fullnameOverride: checkpointz
  replicas: 1

  image:
    repository: ethpandaops/checkpointz
    tag: gloas-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 64m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.1.js" integrity="sha384-icGX6g6CzB0tqlhDc6Su4c6IPVbcbUvfM3xjbbFYsYBwuZR79WkmOxDhGEPfmyn2" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: checkpoint-sync.glamsterdam-devnet-4.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

    tls:
    - hosts:
      - checkpoint-sync.glamsterdam-devnet-4.ethpandaops.io
      secretName: glamsterdam-devnet-4-checkpoint-sync-tls

  config:
    global:
      listenAddr: ":5555"
      logging: "info" # panic,fatal,warm,info,debug,trace
      metricsAddr: ":9090"

    checkpointz:
      mode: full
      caches:
        blocks:
          max_items: 100
        states:
          max_items: 5
      historical_epoch_count: 20

    beacon:
      upstreams:
        - name: bootnode-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-bootnode-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: buildoor-prysm-ethrex-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-buildoor-prysm-ethrex-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: grandine-ethrex-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-grandine-ethrex-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: grandine-nethermind-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-grandine-nethermind-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: lodestar-ethrex-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-lodestar-ethrex-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: lodestar-ethrex-2
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-lodestar-ethrex-2.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: lodestar-nethermind-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-lodestar-nethermind-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: lodestar-nethermind-2
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-lodestar-nethermind-2.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: prysm-ethrex-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-prysm-ethrex-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: prysm-ethrex-2
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-prysm-ethrex-2.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: prysm-nethermind-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-prysm-nethermind-1.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
        - name: prysm-nethermind-2
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>@bn-prysm-nethermind-2.srv.glamsterdam-devnet-4.ethpandaops.io
          dataProvider: true
