# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: https://rpc-bootnode-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-bootnode-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-lighthouse-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: lighthouse-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-lighthouse-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: lodestar-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: lodestar-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-lodestar-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: lodestar-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-nimbus-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: nimbus-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-nimbus-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: nimbus-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-nimbus-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: nimbus-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-prysm-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: prysm-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-prysm-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-prysm-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: prysm-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: teku-ethrex-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-ethrex-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: teku-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-geth-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
- url: https://rpc-teku-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io
  name: teku-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-nethermind-1.srv.glamsterdam-devnet-0.ethpandaops.io:8961
