# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: ethpandaops/dora
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 3Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: dora.glamsterdam-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: glamsterdam-devnet-0
  configPath: "https://config.glamsterdam-devnet-0.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.glamsterdam-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges"
  ethExplorerLink: "https://explorer.glamsterdam-devnet-0.ethpandaops.io"
  publicRpcUrl: "https://rpc.glamsterdam-devnet-0.ethpandaops.io"
  rainbowkitProjectId: "15fe4ab4d5c0bcb6f0dc7c398301ff0e"
  executionGenesisConfig: "https://config.glamsterdam-devnet-0.ethpandaops.io/el/genesis.json"
  apiRequireAuth: False
  apiAuthSecret: "<path:/secrets/services/services.enc.yaml#dora | jsonPath {.api_secret}>"
  apiWhitelistedIPs: []
  apiDefaultRateLimit: 60
  apiDisableDefaultRateLimit: false
  proxyCount: 2
  executionIndexerEnabled: True
  executionIndexerRetention: 336h
  executionIndexerDetailsEnabled: true
  executionIndexerTracesEnabled: True
  executionIndexerDetailsMaxSize: "100GB"
  tracoorUrl: "https://tracoor.glamsterdam-devnet-0.ethpandaops.io"
  tracoorNetwork: "glamsterdam-devnet-0"

  
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: API_CORS_ORIGINS
      value: "*"
    - name: FRONTEND_ENABLE_DAS_GUARDIAN_MASS_SCAN
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
    primary:
      persistence:
        size: "80Gi"

  mevRelays:
    - index: 0
      name: "Flashbots"
      url: "http://mev-relay-1.glamsterdam-devnet-0.ethpandaops.io:9062/"

  authGroups:
    pandaops:
      credentials:
        username: ""
        password: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.glamsterdam-devnets.node_ingress.combined}>"

  blockDbEngine: "s3"
  blockDbConfig:
    endpoint: "<path:/secrets/services/services.enc.yaml#dora | jsonPath {.s3_url}>"
    secure: <path:/secrets/services/services.enc.yaml#dora | jsonPath {.s3_secure}>
    accessKey: <path:/secrets/services/services.enc.yaml#dora | jsonPath {.s3_access_key}>
    secretKey: <path:/secrets/services/services.enc.yaml#dora | jsonPath {.s3_secret_key}>
    bucket: <path:/secrets/services/services.enc.yaml#dora | jsonPath {.s3_bucket}>
    path: "glamsterdam-devnet-0"

  endpointsUrl: "https://raw.githubusercontent.com/ethpandaops/template-devnets/refs/heads/master/kubernetes/devnet-0/dora/endpoints-cl.yaml"
  executionEndpointsUrl: "https://raw.githubusercontent.com/ethpandaops/template-devnets/refs/heads/master/kubernetes/devnet-0/dora/endpoints-el.yaml"
