xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "glamsterdam-devnet-6-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "glamsterdam-devnet-6"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://34e356ff666f501f22fec4eddbdbc4960d15ebe25099f5075420a53282380dbbf5d984fb57932b2fc02bf55c430fb96637cc8624eb6aca754048dd703bb0ed39@137.184.216.66:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
