localhost

[all:vars]
ethereum_network_name=glamsterdam-devnet-0

[bootnode]
bootnode-1 ansible_host=178.105.79.185 ipv6=2a01:4f8:c014:cae3::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True

[lighthouse_reth]
lighthouse-reth-1 ansible_host=178.105.66.240 ipv6=2a01:4f8:c014:7cfc::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=5000 validator_end=5500

[lighthouse_geth]
lighthouse-geth-1 ansible_host=178.104.215.215 ipv6=2a01:4f8:c014:3574::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=500

[lighthouse_nethermind]
lighthouse-nethermind-1 ansible_host=138.201.190.180 ipv6=2a01:4f8:c17:a63b::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=2500 validator_end=3000

[lodestar_reth]
lodestar-reth-1 ansible_host=178.105.71.120 ipv6=2a01:4f8:c014:73f4::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=7000 validator_end=7500

[lodestar_geth]
lodestar-geth-1 ansible_host=178.105.66.212 ipv6=2a01:4f8:c014:8d6::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=2500

[lodestar_nethermind]
lodestar-nethermind-1 ansible_host=192.81.217.50 ipv6=2604:a880:400:d1:0:4:558a:2001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=4500 validator_end=5000

[nimbus_reth]
nimbus-reth-1 ansible_host=46.225.148.18 ipv6=2a01:4f8:c014:a06f::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=6500 validator_end=7000

[nimbus_geth]
nimbus-geth-1 ansible_host=162.55.41.177 ipv6=2a01:4f8:c014:cc61::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=1500 validator_end=2000

[nimbus_nethermind]
nimbus-nethermind-1 ansible_host=178.105.68.98 ipv6=2a01:4f8:c014:2bb::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=4000 validator_end=4500

[prysm_reth]
prysm-reth-1 ansible_host=178.105.75.46 ipv6=2a01:4f8:c014:7eb0::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=5500 validator_end=6000

[prysm_geth]
prysm-geth-1 ansible_host=178.105.68.180 ipv6=2a01:4f8:c014:4::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=500 validator_end=1000

[prysm_nethermind]
prysm-nethermind-1 ansible_host=134.209.71.66 ipv6=2604:a880:400:d1:0:4:558a:3001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=3000 validator_end=3500

[teku_reth]
teku-reth-1 ansible_host=162.243.164.179 ipv6=2604:a880:400:d1:0:4:558a:1001 cloud=digitalocean cloud_region=nyc1 arch=amd64 ethereum_node_cl_supernode_enabled=True validator_start=6000 validator_end=6500

[teku_geth]
teku-geth-1 ansible_host=178.105.65.56 ipv6=2a01:4f8:c014:a09d::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=1500

[teku_nethermind]
teku-nethermind-1 ansible_host=178.105.65.159 ipv6=2a01:4f8:c014:cc6a::1 cloud=hetzner cloud_region=fsn1-dc14 arch=arm64 ethereum_node_cl_supernode_enabled=True validator_start=3500 validator_end=4000


[lighthouse_reth]

# Consensus client groups

[lighthouse:children]
lighthouse_reth
lighthouse_geth
lighthouse_nethermind
[lodestar:children]
lodestar_reth
lodestar_geth
lodestar_nethermind
[nimbus:children]
nimbus_reth
nimbus_geth
nimbus_nethermind
[teku:children]
teku_reth
teku_geth
teku_nethermind
[prysm:children]
prysm_reth
prysm_geth
prysm_nethermind
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
lighthouse_geth
lodestar_geth
nimbus_geth
prysm_geth
teku_geth
[nethermind:children]
lighthouse_nethermind
lodestar_nethermind
nimbus_nethermind
prysm_nethermind
teku_nethermind
[erigon:children]
[reth:children]
[nimbusel:children]
[reth:children]
lighthouse_reth
lodestar_reth
nimbus_reth
prysm_reth
teku_reth

# Global groups

[consensus_node:children]
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
reth
geth
nethermind

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
