# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: https://rpc-bootnode-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-bootnode-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-buildoor-prysm-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: buildoor-prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-buildoor-prysm-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-grandine-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: grandine-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-grandine-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-grandine-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: grandine-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-grandine-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-grandine-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: grandine-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-grandine-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lighthouse-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lighthouse-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lighthouse-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lighthouse-besu-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lighthouse-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lighthouse-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lighthouse-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lodestar-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lodestar-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lodestar-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lodestar-besu-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lodestar-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lodestar-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lodestar-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lodestar-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lodestar-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lodestar-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-lodestar-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: lodestar-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-nimbus-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: nimbus-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-nimbus-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: nimbus-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-nimbus-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: nimbus-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-prysm-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: prysm-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-prysm-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: prysm-besu-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-prysm-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-prysm-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: prysm-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-prysm-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: prysm-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-prysm-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: prysm-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-teku-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: teku-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-besu-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-teku-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: teku-besu-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-besu-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-teku-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: teku-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-geth-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-teku-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: teku-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-geth-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-teku-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io
  name: teku-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-nethermind-1.srv.glamsterdam-devnet-2.ethpandaops.io:8961
- url: https://rpc-teku-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io
  name: teku-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-nethermind-2.srv.glamsterdam-devnet-2.ethpandaops.io:8961
