
nimbusel_container_command_extra_args:
  - --network=/network-config/genesis.json
  - --bootstrap-node={{ ethereum_el_bootnodes | join(',') }}
  - --rpc-api=admin,eth,debug
  - --ws-api=admin,eth,debug
  - --log-level=DEBUG
  - --debug-parallel-state-root=true
  - --debug-bal-state-prefetch=true
  - --debug-bal-parallel-execution=true
