xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: registry-1.docker.io/ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "glamsterdam-sepsf-2-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "glamsterdam-sepsf-2"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://4dfdd89d5514d11576eb6de28164e27bbf17b75b7011a1d2b223f322edd97d2be6eb8b70d2c8650badbc741ba555edc76555ba1d9ffe8e0e8d7ba359d7185700@143.110.240.17:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
