apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powfaucet-agents-data
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-retain
  resources:
    requests:
      storage: 5Gi
